---
apiversion: v1
kind: pod
metadata:
  name: alpine
spec:
  containers:
    -name: alpine1
     image: alpine
     ports:
       -containerport: 80  
     args:
       -sleep
       -1d
    -name: alpine2
     image: alpine
     args:
       -sleep
       -10s   